//@version=3
// https://github.com/balupton/automated-trading
strategy(title="bal--candle-to-renko--strategy", overlay=false, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// ====================================
// STUDY AND STRATEGY

Session = session.regular
Ticker = tickerid(syminfo.prefix, ticker, Session)
RenkoSeries = renko(Ticker, "close", "ATR", 14)
RenkoResolution = input("30", "Renko Resolution", type=resolution)

RenkoOpen = security(RenkoSeries, RenkoResolution, open)
RenkoClose = security(RenkoSeries, RenkoResolution, close)

Up = RenkoOpen < RenkoClose
RenkoColor =  Up ? green : red
plotcandle(RenkoOpen, max(RenkoClose, RenkoOpen), min(RenkoClose, RenkoOpen), RenkoClose, title='renko', color=RenkoColor)

Change = change(RenkoClose)
A = valuewhen(Change, RenkoClose, 1)
B = valuewhen(Change, RenkoClose, 2)
C = valuewhen(Change, RenkoClose, 3)
D = valuewhen(Change, RenkoClose, 4)
E = valuewhen(Change, RenkoClose, 5)
Close1Up = (Change > 0) and (A > B) and (B < C)
Close2Up = (Change > 0) and (A > B and B > C) and (C < D)
Close3Up = (Change > 0) and (A > B and B > C and C < D) and (D < E)
Close1Down = (Change < 0) and (A < B) and (B > C)
Close2Down = (Change < 0) and (A < B and B < C) and (C > D)
Close3Down = (Change < 0) and (A < B and B < C and C < D) and (D > E)

LongEnter = Close2Up
LongExit = Close1Down
ShortEnter = Close2Down
ShortExit = Close1Up

// ====================================
// STRATEGY

strategy.entry("long", strategy.long, when = LongEnter, qty = 100)
strategy.close("long", when = LongExit)
strategy.entry("short", strategy.short, when = ShortEnter, qty = 100)
strategy.close("short", when = ShortExit)

// strategy.risk.max_drawdown(10, strategy.percent_of_equity)
// strategy.close_all(strategy.openprofit < 0)

OpenProfitColor = strategy.openprofit < 0 ? purple : blue
// plot(strategy.openprofit, title = "openprofit", color = OpenProfitColor)

NetProfitColor = strategy.netprofit < 0 ? purple : blue
// plot(strategy.netprofit, title = "netprofit", color = NetProfitColor)
